### ISSUE TITLE
Create Session Two

### ISSUE THREAD

**Issue by pavly-gerges** [Google-Developers-Sohag/Kotlin-I-Sessions#2]

**Comment by AhmedShehatah** [comment]
You've put loops in the first session no porblem with that but I will if there is no time for it in the session. 
In this session we will talk in detial about loops with this order:-
1- importance of loops
2- for loop then while loop then do while loop
3- example get the max number of entered numbers & factorial of a number
4-nested loops 
4- example make maltiplication table.

**Comment by AhmedShehatah** [comment]
factorial example
```.kt
fun main() {
    println("Please enter number: ")
    val n = readLine()!!.toInt()
    var fact = 1
    for (i in 1..n) fact *= i
    println("The factorial of $n = $fact")
}
```

max number example
```.kt
fun main() {
    println("Please enter count of number: ")
    val n = readLine()!!.toInt()
    var mx = Int.MIN_VALUE
    for(i in 1..n){
        val x = readLine()!!.toInt()
        if(x>mx)
            mx = x
    }
    println("The max number entered is $mx")

}
```
multiplication table example
```.kt
fun main() {
    for(i in 1..12){
        println("Table NO #$i")
        for(j in i..12){
            println("$i * $j = ${i*j}")
        }
        println("||~~~~~~~~~~~~~~~~~~~~~~~~||")
    }
}

```

**Comment by pavly-gerges** [comment]
> factorial example
> 
> fun main() { println("Please enter number: ") val n = readLine()!!.toInt() var fact = 1 for (i in 1..n) fact *= i println("The factorial of $n = $fact") }
> 
> max number example
> 
> fun main() { println("Please enter count of number: ") val n = readLine()!!.toInt() var mx = Int.MIN_VALUE for(i in 1..n){ val x = readLine()!!.toInt() if(x>mx) mx = x } println("The max number entered is $mx")
> 
> }
> 
> multiplication table example fun main() { for(i in 1..12){ println("Table NO #$i") for(j in i..12){ println("$i * $j = ${i*j}") } println("||~~~~~~~~~~~~~~~~~~~~~~~~||") } }

Should we finish basics first before going deeper into mathematics ? I would like to teach them functions and returns in this session to finish kotlin basics, then we might be able to do these examples using functions which would make sense...

**Comment by pavly-gerges** [comment]
Literally all things in kotlin are infix and inline functions.

**Comment by pavly-gerges** [comment]
readLine() and toInt() are functions, so teaching basic functions at first may be a good practice.

**Comment by AhmedShehatah** [comment]
we will make a separated session for functions, and it's just a simple example for loops, if you have simpler examples i would be happy to see them
readLine(), toInt() we will just explan that if you want to convert your input to int you should write toInt(), and to take input from user just write readLine() we will not go deeper in function

**Comment by pavly-gerges** [comment]
@Ahmedshehatah By the way, to type coding blocks on git use 3 back ticks before your code, and add your language extension then your code, then 3 back ticks after your code : 
```kt
fun main() {
println("Please enter number: ")
val n = readLine()!!.toInt()
var fact = 1
for (i in 1..n) fact *= i
println("The factorial of $n = $fact")
}
```
```
```<optional language>
//your code here
```    

Read this about code blocks : 
https://hub.jmonkeyengine.org/t/how-to-type-code-blocks/31155?u=pavl_g

**Comment by AhmedShehatah** [comment]
OK :+1:  thanks
